# Generated by Django 3.1.4 on 2021-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.UUIDField(default='6049b9a4', editable=False, primary_key=True, serialize=False),
        ),
    ]
