# Generated by Django 3.1.4 on 2021-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20210401_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.UUIDField(default=175, editable=False, primary_key=True, serialize=False),
        ),
    ]
