# Generated by Django 3.1.4 on 2021-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20210401_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.UUIDField(default=76, editable=False, primary_key=True, serialize=False),
        ),
    ]
