# Generated by Django 3.1.4 on 2021-04-01 13:58

from django.db import migrations, models
import url.models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20210401_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.UUIDField(default=url.models.unique_rand, editable=False, primary_key=True, serialize=False),
        ),
    ]
