# Generated by Django 3.1.4 on 2021-04-01 14:50

from django.db import migrations, models
import url.models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0006_auto_20210401_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.CharField(default=url.models.unique_rand, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
